### ISSUE TITLE
incorrect formatting inside data- attribute

### ISSUE THREAD

**Issue by leider** [prettier/plugin-pug#55] opened 2020-01-04 15:05 UTC
`option(data-content='<span class="' + cssIconClass(val) + '"></span><span class="text-' + cssColorCode(val) + '"> ' + val + '</span>')` is formatted to `option(
          data-content="<span class=\"' + cssIconClass(val) + '\"></span><span class=\"text-' + cssColorCode(val) + '\"> ' + val + '</span>"
        )`

**Comment by Shinigami92** [comment] 2020-01-04 15:06
could be a duplicate of #54

**Comment by leider** [comment] 2020-01-04 15:07
Definitely. Just another test-case for you.

**Comment by Shinigami92** [comment] 2020-01-08 08:40
I added another sentence to my README.md (https://github.com/prettier/plugin-pug/commit/6b0f555e3b824aa4564a6312594f574f05611402)

You should use
```pug
option(data-content=`<span class="'${cssIconClass(val)}'"></span><span class="text-'${cssColorCode(val)}'"> '${val}'</span>`)
```

in your code

I will merge Issue #53, #54 and #55 (this issue) into one new Issue to track the base problem

**Comment by Shinigami92** [comment] 2020-01-08 08:45
Closing as predecessor of #58

**Closed by Shinigami92** 2020-01-08 08:45 UTC
