### ISSUE TITLE
add option to disable automatic inline of class names

### ISSUE THREAD

**Issue by basaran** [prettier/plugin-pug#165] opened 2020-11-28 07:42 UTC
## Request / Idea

Some editor extensions are having a tough time providing intellisense auto completions (vetur) when the intellisense is invoked inline on a `pug` file.

This is not an issue with the `plugin-pug`, but it would be extremely helpful to have an option to disable inlining of css class names during development.

Option can be called something like `pugTagCss`

Please see the recording:

![inline_classes](https://user-images.githubusercontent.com/30809170/100496518-bb8a8a80-3122-11eb-9125-d3b43e5d0532.gif)

**Comment by Shinigami92** [comment] 2020-11-28 07:56
Duplicate of #36 
But can you copy your gif and explanation as a comment into the other issue?
This will increase the priority much!

**Closed by Shinigami92** 2020-11-28 07:56 UTC

**Comment by basaran** [comment] 2020-11-28 09:09
Sure thing, and also please let me know if you would accept a PR for this?

**Comment by Shinigami92** [comment] 2020-11-28 09:11
I'm **always** happy about PRs 😃
Also look into the one PR already opened and the discussion in the other issue 🙂

**Comment by basaran** [comment] 2020-11-28 09:45
Great, it seems he already made progress and is planning to include a regex option as well. He should be done soon, I will not create noise. Thank you.

```
for (const className of classes) {
						if (!this.options.pugUseClassLiterals || !validClassNameRegex.test(className)) {
							specialClasses.push(className);
						} else {
							normalClasses.push(className);
						}
					}
```
