### ISSUE TITLE
Bug: Trailing whitespace in tags is not trimmed

### ISSUE THREAD

**Issue by ofk** [prettier/plugin-pug#425] opened 2023-01-04 04:25 UTC
### Plugin Version

v2.3.0

### Prettier Version

v2.8.1

### Which frameworks are affected?

- [X] none
- [ ] vue
- [ ] angular
- [ ] svelte

### Node Version

v16.17.0

### Which operating systems have you used?

- [ ] Linux
- [X] macOS
- [ ] Windows

### Prettier config

```json
{

}
```

### Input

```pug
html
  body
    p 
      a Link
```

### Output or Error

```bash
html
  body
    p 
      |
      a Link
```

### Expected Output

```pug
html
  body
    p
      a Link
```

### Additional Context

Note the mixed whitespace immediately following the `p` element.
The major problem with this bug is that running prettier on this output yields an even different result (more pipes).

**Comment by Shinigami92** [comment] 2023-01-04 08:16
Ah I assume the most important part here is that after the `p` tag is a trailing whitespace (`p `)
Will add a test for this later and try to fix it if I can reproduce it

**Comment by Shinigami92** [comment] 2023-01-05 09:39
@ofk For me the output is

```pug
html
  body
    p
      |
      a Link
```

and not

```ts
html
  body
    p 
      |
      a Link
```

So it looks like it correctly transforms the whitespace after the `p` tag into a `|`, which is documented here: https://pugjs.org/language/plain-text.html#whitespace-control

Please confirm that this could solve your issue and then close it, otherwise please explain more deeply what your issue is

**Comment by ofk** [comment] 2023-01-13 15:16
Sorry for the late response.

Your output may be more appropriate.
The biggest problem with this input is that the result changes with each run of prettier.
Therefore, if multiple runs do not change the results, I am fine with any modification.

## Input

```
html
  body
    p 
      a Link
```

## First prettier output

```
html
  body
    p 
      |
      a Link
```

## Second prettier output (or apply prettier to first prettier output)

```
html
  body
    p 
      |
      |
      a Link
```

## Third prettier output (or apply prettier to second prettier output)

```
html
  body
    p 
      |
      |
      |
      a Link
```

**Comment by Shinigami92** [comment] 2023-01-13 16:24
@ofk AHA, that is an important info!
I need to update the test to run the formatter twice then
If I find the time, will do this this weekend :+1:

**Closed** 2023-01-20 18:56 UTC
