### ISSUE TITLE
Any chance to get it work with vue single components?

### ISSUE THREAD

**Issue by xorik** [prettier/plugin-pug#5] opened 2019-06-27 17:08 UTC
Prettier works perfectly for the `<script>` tag of vue single-file compontens (.vue files), but it seems like this plugin doesn't work with vue's `<template lang="pug">`.

Do you know if it's possible to make it work?

**Comment by Shinigami92** [comment] 2019-06-28 13:38
Currently you can use the workaround `<template lang="pug" src="./index.pug"></template>`

But to leave this here, I think a good start for a PR could be: https://github.com/prettier/prettier/blob/master/src/language-html/syntax-vue.js

**Comment by Shinigami92** [comment] 2019-07-14 14:17
@xorik Is it okay for you to use the workaround? Or does it have a high priority?
If you use the workaround, it's also a more native feeling :)

@j-f1 I created a test (locally) and tried to inspect if anything was called in my plugin. But it doesn't call anything 🤔 
I thought the [`embed`](https://github.com/prettier/plugin-pug/blob/1697fae6e7a47d2b1b7136082b1fb684b6f8deb7/src/index.ts#L526-L534) function is for this... But nope.
[markdown formatting is working!](https://github.com/prettier/plugin-pug/blob/1697fae6e7a47d2b1b7136082b1fb684b6f8deb7/test/embed/md/embed.test.ts#L10)

My test:
```vue
<template lang="pug">
div(class="abc")
  | {{ msg }}
</template>

<script>
export default {
  data() {
    msg: 'test';
  }
};
</script>
```

```js
import { format } from 'prettier';
import { plugin } from './../../../src/index';
// ...
const actual: string = format(code, { parser: 'vue', plugins: [plugin], singleQuote: true });
// ...
```

Result should be that `div(class="abc")` formats to `.abc`, but I cant see any logs from my plugin. It is not invoked.

**Comment by xorik** [comment] 2019-07-14 14:29
@Shinigami92 it would be super nice if I could use prettier with your plugin without dividing each vue file to template + script.
I'm not familiar with prettier internal API, but I could try my best to fix this bug. Prettier works with HTML and javascript/typescript sections of vue files without any issues.

Maybe I could try to make an issue to the prettier repo?

**Comment by Shinigami92** [comment] 2019-07-14 14:34
@xorik Yes, maybe you should do that and refer to this issue.

At the moment, I don't really know if it's on the plugin side or on the prettier core side.

I'm surprised that Markdown's formatting works, and that I did nothing to support it.

**Comment by xavxyz** [comment] 2019-10-01 10:01
> But it doesn't call anything 🤔 I thought the `embed` function is for this... But nope.

👋, I may have found a hint for us wanting to use `@prettier/plugin-pug` and Vue templates!

https://github.com/prettier/prettier/issues/5371 references a time where there were troubles with Vue templates written with Pug, Prettier formatting Pug templates as HTML templates. 

It got fixed by ignoring `template` tags with a `lang` attribute different to `html`: https://github.com/prettier/prettier/pull/5388/files#diff-0558c7e4048f9cad5b9156aecca77883R40-R47 

Now that we have awesome plugins in beta, could the plugin somehow extend the list of usable lang attributes?

Or should a modification be done directly to `prettier/language-html/utils` (where the check happens on `lang` attribute in the mentioned PR)?

I would be happy to help for this issue, but I don't know where to start (yet)! 💯

**Comment by Shinigami92** [comment] 2019-10-01 11:28
Please present this to @prettier/core in the related issue https://github.com/prettier/prettier/issues/6298

I think this is the right way 👍 

In my opinion I would suggest to create something like `prettier/language-pug/utils`.
I dont think I can _patch_ something like this from **this** plugin.

**Comment by xavxyz** [comment] 2019-10-01 12:16
> I dont think I can patch something like this from this plugin.

I get it! 😄 

Thanks, 🎩

**Comment by MentalGear** [comment] 2020-05-09 17:19
Native single vue file integration would be nice! Any news on this?

**Comment by Shinigami92** [comment] 2020-05-13 12:13
An update for everyone who is waiting for this functionality:
I defined a prototype test and added a comment to it

https://github.com/prettier/plugin-pug/blob/5da540b15e1974fe169e4cd58d796e38a5babac3/test/embed/vue/embed.test.ts#L7-L8

You can also see in the same file that `html` is working

---

So the problem is that my plugin is not notified that `<template lang="pug">` should be formatted using this plugin.

**Comment by Shinigami92** [comment] 2020-07-15 09:05
@fisker Is there an ETA when users can profit from your merge?
https://github.com/prettier/prettier/pull/8465

I think we are waiting on a new prettier `2.1.0` release, do we?

**Comment by fisker** [comment] 2020-07-15 09:16
Yes, we still need wait for `v2.1.0` release, and I don't know the schedule.

Good news is Prettier support install from the repo, so this should work.

```js
yarn add prettier/prettier @prettier/plugin-pug
npx prettier test.vue --write
```

**Comment by Shinigami92** [comment] 2020-07-15 10:16
@fisker Yes, I know that this is working.
But I mean waiting for production and global avaiability

**Comment by fisker** [comment] 2020-07-15 10:20
We'll have to wait.

**Comment by Shinigami92** [comment] 2020-08-28 07:47
With prettier v2.1 pug within template can now be formatted

**Closed by Shinigami92** 2020-08-28 07:47 UTC
Labels: framework: Vue, help wanted, type: enhancement
