### ISSUE TITLE
Bug: singleQuote doesn't affect mixin parameters

### ISSUE THREAD

**Issue by wscherphof** [prettier/plugin-pug#332] opened 2022-01-21 13:28 UTC
### Plugin Version

1.19.2

### Prettier Version

2.5.1

### Which frameworks are affected?

- [X] none
- [ ] vue
- [ ] angular
- [ ] svelte

### Node Version

16

### Which operating systems have you used?

- [X] Linux
- [ ] macOS
- [ ] Windows

### Prettier config

```json
{
  "singleQuote": true
}
```

### Input

```pug
mixin form(method, action, target, push)
  - methodOverride = method != 'GET' && method != 'POST';
  - push = push ? 'true' : false;
  form(
    method=methodOverride ? 'POST' : method,
    action=action,
    hx-target=target,
    hx-push-url=push
  )&attributes(attributes)
    if methodOverride
      //- _method is from
      //- https://www.npmjs.com/package/fastify-method-override
      input(type='hidden', name='_method', value=method)
    block

mixin get(action, target, push)
  +form("GET", action, target, push)&attributes(attributes)
    block
```

### Output or Error

```bash
✔️ strings in JavaScript code get singleQuote
✔️ attribute values get singleQuote
❌ mixin arguments remain double-quoted
```

### Expected Output

```pug
✔️ mixin arguments get singleQuote as well
```

### Additional Context

also, pugSingleQuote doesn't work - #174

**Comment by Shinigami92** [comment] 2022-01-21 13:31
Duplicate of #66

See https://github.com/prettier/plugin-pug/issues/66#issuecomment-583826898

**Closed by Shinigami92** 2022-01-21 13:31 UTC
