### ISSUE TITLE
Bug: Multiline inline script throws TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by silveoj** [prettier/plugin-pug#156] opened 2020-11-10 18:55 UTC
## Info

| Tool      | Version                 |
| --------- | ----------------------- |
| Framework | none |
| Node      | v10.14 - 14.13                  |
| OS        | win10           |

```
    "eslint": "7.13.0",
    "eslint-plugin-pug": "1.2.2",
    "prettier": "2.1.2",
    "@prettier/plugin-pug": "1.10.1",
```

## Eslint config
```
{
  "parserOptions": {
    "ecmaVersion": 2018
  },
  "env": {
      "es6": true
  },
  "plugins": [
    "prettier",
    "pug"
  ],
  "extends": [
      "plugin:prettier/recommended"
  ],
  "rules": {
      "prettier/prettier": [
        "error",
        {
            "usePrettierrc": true
        }
      ]
  }
}
```
There is no error if I remove `extends` and `rules`.`prettier/prettier`

## Prettier config

```json
{
  "printWidth": 120,
  "endOfLine": "auto"
}
```
If I use `{}` config I don't see error.

I use this command with this `eslint` config:
- `eslint --ext .js,.pug \"./src\"` - doesn't work
- `eslint --ext .js\"./src\"` - works
- `eslint --ext .pug \"./src\"` - works

## Input

doesn't work (with more than one line). We can have function body or not - there is always error.
```pug
script.
  function foo() {
  }
```

works
```
script.
  function foo() {}
```

## Output or Error
I get error for multiline inline script
```
TypeError: Cannot read property '0' of undefined
    at Object.exports.transformFix (.\node_modules\eslint-plugin-pug\utils.js:115:72)
    at .\node_modules\eslint-plugin-pug\utils.js:135:25
    at arrayEach (.\node_modules\lodash\lodash.js:516:11)
    at Function.forEach (.\node_modules\lodash\lodash.js:9368:14)
    at .\node_modules\eslint-plugin-pug\utils.js:128:7
    at arrayEach (.\node_modules\lodash\lodash.js:516:11)
    at Function.forEach (.\node_modules\lodash\lodash.js:9368:14)
    at exports.postprocess (.\node_modules\eslint-plugin-pug\utils.js:126:5)
    at Linter._verifyWithProcessor (.\node_modules\eslint\lib\linter\linter.js:1327:16)
    at Linter._verifyWithConfigArray (.\node_modules\eslint\lib\linter\linter.js:1264:25)
```

Thanks.
I see `[0]` in `eslint-plugin-pug\utils.js` So I created issue for this prettier plugin.

**Comment by Shinigami92** [comment] 2020-11-10 19:00
I'll try to do it by the weekend at the latest, if nothing gets in my way

**Comment by Shinigami92** [comment] 2020-11-14 11:05
I have written a [test](https://github.com/prettier/plugin-pug/pull/157/files) and everything seems to [work](https://github.com/prettier/plugin-pug/pull/157/checks?check_run_id=1399657517#step:9:37) just fine without errors.
Maybe this is not a problem caused by this plugin, but [eslint-plugin-pug](https://github.com/myfreeweb/eslint-plugin-pug#readme)? :thinking: 
You should open an issue there and link it to this issue.

**Comment by Shinigami92** [comment] 2020-11-20 12:07
Any news about this?
Please do not hesitate to close this issue yourself so that I don't have to be rude and forcibly close it on my side :slightly_smiling_face:

**Comment by Shinigami92** [comment] 2020-11-20 12:08
@silveoj Any news about this?
Please do not hesitate to close this issue yourself so that I don't have to be rude and forcibly close it on my side :slightly_smiling_face:

**Closed** 2020-11-24 20:17 UTC
Labels: needs clarification
