### ISSUE TITLE
Bug: What's wrong? This code can't be formatted

### ISSUE THREAD

**Issue by tucke** [prettier/plugin-pug#144] opened 2020-10-27 03:20 UTC
## Info

| Tool     | Version       |
| -------- | ------------- |
| Plugin   | v1.10.0        |
| Prettier | v2.1.2        |
| Node     | v14.14.0        |
| OS       | mac |

## Input

```
div(class="icons-container")
    aside
          a(href="#"             target="_blank") Add and use
    el-tabs(type="border-card")
      el-tab-pane(label="Icons")
        div(v-for="item of svgIcons"         :key="item")
          el-tooltip(placement="top")
            div(slot="content") {{ generateIconCode(item) }}
            div(class="icon-item")
              svg-icon(:icon-class="item"     class="disabled")
              span {{ item }}
      el-tab-pane(label="Element-UI Icons")
        div(v-for="item of elementIcons" :key="item")
          el-tooltip(placement="top")
            div(slot="content") {{ generateElementIconCode(item) }}
            div(class="icon-item")
              i(:class="'el-icon-' + item")
              span {{ item }}
```

## Expected Output

```
.icons-container
  aside
    a(href="#", target="_blank") Add and use
  el-tabs(type="border-card")
    el-tab-pane(label="Icons")
      div(v-for="item of svgIcons", :key="item")
        el-tooltip(placement="top")
          div(slot="content") {{ generateIconCode(item) }}
          .icon-item
            svg-icon.disabled(:icon-class="item")
            span {{ item }}
    el-tab-pane(label="Element-UI Icons")
      div(v-for="item of elementIcons", :key="item")
        el-tooltip(placement="top")
          div(slot="content") {{ generateElementIconCode(item) }}
          .icon-item
            i(:class="'el-icon-' + item")
            span {{ item }}
```

## Additional Context
There seems to be no work！why？

**Comment by Shinigami92** [comment] 2020-10-27 05:42
Duplicate of #129 
Try to workaround it with `in` instead of `of`

**Closed by Shinigami92** 2020-10-27 05:42 UTC

**Comment by tucke** [comment] 2020-10-27 05:48
@Shinigami92  thank you
