### ISSUE TITLE
Vue Integration?

### ISSUE THREAD

**Issue by MentalGear** [prettier/plugin-pug#81] opened 2020-05-09 17:15 UTC
## Request / Idea
Could we get a guide on vue cli integration, please ?

**Comment by Shinigami92** [comment] 2020-05-09 17:21
I would suggest to outsource your pug file with:

```html
<template lang="pug" src="./file.pug" />
```

This is how you get the best language support for `.pug` files directly.

Maybe this is a duplicate of https://github.com/prettier/plugin-pug/issues/5?

**Comment by MentalGear** [comment] 2020-05-09 17:23
Yes, I read about this little workaround, though it would be great if we could keep a single file structure. I think you also offered to work on it, did you have any luck with integrating it? :)

**Comment by Shinigami92** [comment] 2020-05-09 17:25
I haven't checked that again. Could try adding a test in the next few days.  
I don't have much experience with vue single files because I always use my workaround as the default.

**Closed** 2020-08-28 07:47 UTC
Labels: framework: Vue, type: duplicate
